version: '3'

name: "app"

services:
  cm-web:
    container_name: cm-web
    build:
      context: .
      args:
        ENV: prod
    networks:
      - internal
    ports:
      - 127.0.0.1:3001:80

networks:
  internal:
    external: true
    name: internal
