apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bytebase-web
  name: bytebase-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bytebase-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bytebase-web
    spec:
      containers:
        - image: bytebase/bytebase:0.13.0
          name: bytebast-webapp
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /ec2
              name: ec2-vol
          resources: {}
          ports:
            - containerPort: 8080
      volumes:
        - name: ec2-vol
          # This AWS EBS volume must already exist.
          awsElasticBlockStore:
            volumeID: "vol-0394341534aaa6650"
            fsType: ext4

status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: bytebase-web
  labels:
    run: bytebase-web
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: bytebase-web
  type: LoadBalancer
