apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-cm
  namespace: cloudmatiq
  labels:
    app: eks-cm-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-cm-web
  template:
    metadata:
      labels:
        app: eks-cm-web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: cm-web
          image: 516627972637.dkr.ecr.ap-south-1.amazonaws.com/cm-web:latest
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
