apiVersion: v1
kind: Service
metadata:
  name: eks-cm-service
  namespace: cloudmatiq
  labels:
    app: eks-cm-web
spec:
  selector:
    app: eks-cm-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80