        name: build_test_01

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            
# No SonarQube configuration found for this project type.

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [SONARQUBE]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "CmCICD#2024#" ssh -p 222 -o StrictHostKeyChecking=no ubuntu@51.20.190.94 <<EOF
                              cd ~/projects/apps/angularProject/
                              sudo npm install                                     
                              sudo ng build 
                    EOF