name: docker_test

on:
  workflow_dispatch:

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

  #---------------- SONARQUBE
  SONARQUBE:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: sqp_d5c17085de7fd62151dcac07600573c7c9ca70cc
          SONAR_HOST_URL: http://56.228.14.44:9000
  
  #---------------- BUILD_SCRIPT
  BUILD_SCRIPT:
    needs: [SONARQUBE]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Build on Remote VM and Copy Artifacts
        run: |
          # 1. Run build on remote VM
          sshpass -p "a7X2p9L4kR" ssh -p 222 -o StrictHostKeyChecking=no omnisecure@56.228.14.44 <<EOF
            cd ~/projects/apps/sample_project
            source ~/.nvm/nvm.sh
            nvm use default
            rm -rf node_modules package-lock.json dist
            npm install
            ng build --configuration=production --output-path=dist/cloudmatiq-web
            ls -la dist/cloudmatiq-web/
          EOF
          
          # 2. Copy artifacts to GitHub runner
          mkdir -p ./dist
          sshpass -p "a7X2p9L4kR" scp -P 222 -r \
            omnisecure@56.228.14.44:/home/omnisecure/projects/apps/sample_project/dist/cloudmatiq-web \
            ./dist/
          
          # 3. Verify files and upload as artifact
          ls -la ./dist/cloudmatiq-web/
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-build-artifacts
          path: ./dist/cloudmatiq-web/
 
  #---------------- DOCKER
  DOCKERHUB:
    needs: [BUILD_SCRIPT]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: web-build-artifacts
          path: ./dist/cloudmatiq-web/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: devtester2025
          password: dckr_pat_W9cx0PiYuv_5BgW54h7oBv1viCU
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: devtester2025/pipelinev1:main
          
  #---------------- VIRTUAL_MACHINE
  VIRTUAL_MACHINE:
    needs: [DOCKERHUB]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Linux Server
        run: |
          sshpass -p "CmCICD#2024#" ssh -o StrictHostKeyChecking=no ubuntu@13.51.7.24 \
            "sudo docker pull devtester2025/pipelinev1:main && \
             sudo docker run --rm -p 222:222 -d devtester2025/pipelinev1:main"
