name: docker_test

on:
  workflow_dispatch:

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

  #---------------- SONARQUBE
  SONARQUBE:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: sqp_d5c17085de7fd62151dcac07600573c7c9ca70cc
          SONAR_HOST_URL: http://56.228.14.44:9000
  
  #---------------- BUILD_SCRIPT
  BUILD_SCRIPT:
    needs: [SONARQUBE]
    runs-on: ubuntu-latest
    steps:
      - name: Run script on the VM
        run: |
          # 1. Run build on VM
          sshpass -p "a7X2p9L4kR" ssh -p 222 omnisecure@56.228.14.44 <<EOF
            cd ~/projects/apps/sample_project
            rm -rf dist
            npm run build-prod  # Ensure this outputs to dist/cloudmatiq-web
            ls -la dist/cloudmatiq-web/  # Verify files exist
          EOF

          # 2. Download artifacts to GitHub runner
          mkdir -p ./usr/src/app/dist  # <- Docker expects files here
          sshpass -p "a7X2p9L4kR" scp -P 222 -r \
            omnisecure@56.228.14.44:/home/omnisecure/projects/apps/sample_project/dist/cloudmatiq-web \
            ./usr/src/app/dist/

          # 3. Verify files are in the right place for Docker
          ls -la ./usr/src/app/dist/cloudmatiq-web/
 
 #---------------- DOCKER
  DOCKERHUB:
    needs: [BUILD_SCRIPT]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: devtester2025
          password: dckr_pat_W9cx0PiYuv_5BgW54h7oBv1viCU

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: devtester2025/pipelinev1:main
          
  #---------------- VIRTUAL_MACHINE
  VIRTUAL_MACHINE:
    needs: [DOCKERHUB]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Linux Server
        run: |
          sshpass -p CmCICD#2024# ssh -o StrictHostKeyChecking=no ubuntu@13.51.7.24 "sudo docker pull devtester2025/pipelinev1:main && sudo docker run --rm -p 222:222 -d devtester2025/pipelinev1:main"
