        name: DR_test_01

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

    #---------------- SONARQUBE
          SONARQUBE:
            needs: [build]
            runs-on: ubuntu-latest
            environment:
              name: DEVELOPMENT
            steps:
              - uses: actions/checkout@v3
              - name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
            env:
                SONAR_TOKEN: sqp_d5c17085de7fd62151dcac07600573c7c9ca70cc
                SONAR_HOST_URL: http://51.20.115.75:9000

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [SONARQUBE]
            runs-on: ubuntu-latest
            steps:
               - name: Retry Run script on the VM
                 uses: nick-fields/retry@v2
                 with:
                   timeout_seconds: 300
                   max_attempts: 2
                   retry_on: error
                   command: |
                    sshpass -p "a7X2p9L4kR" ssh -p 222 -o StrictHostKeyChecking=no omnisecure@51.20.115.75 <<EOF
                            cd ~/projects/apps/sample_project
                              source ~/.nvm/nvm.sh
                              nvm use default
                              node -v
                              cd ~/projects/apps/sample_project
                              pwd
                              rm -rf node_modules package-lock.json dist
                              npm install
                              ng build
                              export BUILD_TIMESTAMP=\$(TZ="Asia/Kolkata" date +"%d-%b-%Y_%H:%M:%S")
                              echo "Uploading to FTP: cicd_test/\${BUILD_TIMESTAMP}/"
                              sshpass -p "Admin123!" sftp -oPort=222 \
                                -o StrictHostKeyChecking=no \
                                -o UserKnownHostsFile=/dev/null \
                                barathansnkl@gmail.com@192.168.1.1 <<SFTP_EOF
                              mkdir cicd_test/\${BUILD_TIMESTAMP}
                              put -r cicd_test* cicd_test/\${BUILD_TIMESTAMP}
                              bye
                              SFTP_EOF 
                    EOF 