        name: release_retry_06

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [build]
            runs-on: ubuntu-latest
            steps:
               - name: Retry Run script on the VM
                 uses: nick-fields/retry@v2
                 with:
                   timeout_seconds: 5
                   max_attempts: 3
                   retry_on: error
                   command: |
                    sshpass -p "CmCICD#2024#" ssh -p undefined -o StrictHostKeyChecking=no ubuntu@13.51.7.24 <<EOF
                            cd ~/projects/script_test/javaproject/Spring-Boot-main
                              sudo mvn clean
                              sudo mvn install 
                    EOF 

        #---------------- DOCKER
          DOCKERHUB:
           needs: [BUILD_SCRIPT]
           runs-on: ubuntu-latest
           environment:
              name: DEVELOPMENT
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: devtester2025
                 password: dckr_pat_W9cx0PiYuv_5BgW54h7oBv1viCU
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: devtester2025/cicd_js:main
            