        name: retry_test_01

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [build]
            runs-on: ubuntu-latest
            steps:
               - name: Retry Run script on the VM
                 uses: nick-fields/retry@v2
                 with:
                   timeout_seconds: 60
                   max_attempts: 2
                   retry_on: error
                   command: |
                    sshpass -p "a7X2p9L4kR" ssh -p 222 -o StrictHostKeyChecking=no omnisecure @51.20.72.247 <<EOF
                              cd ~/projects/apps/sample_project
                              rm -rf node_modules package-lock.json dist
                              npm install
                              ng build 
                    EOF