        name: Rollback_Test8

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

    #---------------- SONARQUBE
          SONARQUBE:
            needs: [build]
            runs-on: ubuntu-latest
            environment:
              name: DEVELOPMENT
            steps:
              - uses: actions/checkout@v3
              - name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
            env:
                SONAR_TOKEN: sqp_d5c17085de7fd62151dcac07600573c7c9ca70cc
                SONAR_HOST_URL: http://51.21.247.48:9000

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [SONARQUBE]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "a7X2p9L4kR" ssh -o StrictHostKeyChecking=no omnisecure@51.21.247.48 <<EOF
                              cd ~/projects/apps/sample_project
                              source ~/.nvm/nvm.sh
                              nvm use default
                              node -v
                              cd ~/projects/apps/sample_project
                              pwd
                              rm -rf node_modules package-lock.json dist
                              npm install
                              ng build 
                   EOF