name: Rollback_Test2

on:
  workflow_dispatch:

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  BUILD_SCRIPT:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Run build script on VM over SSH
        run: |
          sshpass -p "a7X2p9L4kR" ssh -p 222 -o StrictHostKeyChecking=no omnisecure@51.21.247.48 << 'ENDSSH'
            cd ~/projects/apps/sample_project
            source ~/.nvm/nvm.sh
            nvm use default
            node -v
            pwd
            rm -rf node_modules package-lock.json dist
            npm install
            ng build
          ENDSSH

      - name: Upload build to FTP Server
        env:
          FTP_SERVER: 51.21.247.48
          FTP_USERNAME: omnisecure
          FTP_PASSWORD: a7X2p9L4kR
          REMOTE_PATH: '/ftp/deploy'
          LOCAL_FILE: 'dist/angular-conduit/app.zip'
        run: |
          echo "Uploading build via FTP..."
          apt-get update && apt-get install -y ftp
          ftp -inv $FTP_SERVER <<EOF
          user $FTP_USERNAME $FTP_PASSWORD
          cd $REMOTE_PATH
          put $LOCAL_FILE
          bye
          EOF
