        name: test1

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            
# No SonarQube configuration found for this project type.

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [SONARQUBE]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "build_001" ssh -p undefined -o StrictHostKeyChecking=no build@192.168.1.133 <<EOF
                              test 
                   EOF

        #---------------- DOCKER
          DOCKERHUB:
           needs: [BUILD_SCRIPT]
           runs-on: ubuntu-latest
           environment:
              name: DEVELOPMENT
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: devtester202
                 password: dckr_pat_W9cx0PiYuv_5BgW54h7oBv1viCU
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: devtester202/undefined:main
            

      #---------------- VIRTUAL_MACHINE
          VIRTUAL_MACHINE:
            runs-on: ubuntu-latest
            environment:
              name: DEVELOPMENT
            needs: [DOCKERHUB]
            steps:
               - name: Checkout code
                 uses: actions/checkout@v3
               - name: Deploy to Linux Server
                 run: |
                     sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IPADDRESS }} "sudo docker pull devtester202/undefined:main && sudo docker run --rm -p undefined:undefined -d devtester202/undefined:main"