        name: test_release_sonarqube1

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

    #---------------- SONARQUBE
          SONARQUBE:
            needs: [build]
            runs-on: ubuntu-latest
            environment:
              name: DEVELOPMENT
            steps:
              - uses: actions/checkout@v3
              - name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
            env:
                SONAR_TOKEN: sqp_d5c17085de7fd62151dcac07600573c7c9ca70cc
                SONAR_HOST_URL: http://51.20.132.12:9000/

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [SONARQUBE]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "CmCICD#2024#" ssh -o StrictHostKeyChecking=no ubuntu@13.51.7.24 <<EOF
                              cd ~/projects/script_test/javaproject/Spring-Boot-main
                              sudo mvn clean
                              sudo mvn install 
                   EOF

        #---------------- DOCKER
          DOCKERHUB:
           needs: [BUILD_SCRIPT]
           runs-on: ubuntu-latest
           environment:
              name: DEVELOPMENT
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: ${{ vars.DOCKER_USERNAME }}
                 password: ${{ vars.DOCKER_ACCESSTOKEN }}
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: ${{ vars.DOCKER_USERNAME }}/cicd_js:main

      #---------------- VIRTUAL_MACHINE
          VIRTUAL_MACHINE:
            runs-on: ubuntu-latest
            environment:
              name: DEVELOPMENT
            needs: [DOCKERHUB]
            steps:
               - name: Checkout code
                 uses: actions/checkout@v3
               - name: Deploy to Linux Server
                 run: |
                     sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IPADDRESS }} "sudo docker pull ${{ vars.DOCKER_USERNAME }}/cicd_js:main && sudo docker run --rm -p 22:22 -d ${{ vars.DOCKER_USERNAME }}/cicd_js:main"